# Generated by Django 6.0.1 on 2026-02-06 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20),
        ),
    ]
