# Generated by Django 6.0.1 on 2026-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_tarefa_concluida_tarefa_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
