# Generated by Django 6.0.1 on 2026-02-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_tarefa_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
